name: EOL JS Scan (Reusable)

on:
  workflow_call:
    inputs:
      suppression:
        description: 'Path to the suppression.xml file'
        required: false
        type: string
      npm-run-cmd:
        description: 'NPM command to run'
        required: true
        type: string
    secrets:
      github-token:
        description: 'GitHub token for creating/updating comments'
        required: true
      nvd-api-key:
        description: 'NVD API key for the dependency check'
        required: false

jobs:
  filter:
    name: Get changed files
    runs-on: ubuntu-latest

    outputs:
      run-scan: ${{ steps.filter.outputs.dependencies }}

    steps:
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dependencies:
              - 'package-lock.json'
              - 'app-v2/package-lock.json'
              - '**/bower_components/**'
              - 'suppression.xml'

  scan:
    name: Run EOL/Outdated JS Scanner
    needs: filter
    if: needs.filter.outputs.run-scan == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Cache node_modules
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: ${{ inputs.npm-run-cmd }}

      - name: Run EOL/Outdated JS Scan
        uses: fylein/eol-outdated-js-scan-action@master
        with:
          github-token: ${{ secrets.github-token }}
          suppression: ${{ inputs.suppression }}
          nvd-api-key: ${{ secrets.nvd-api-key }}